### ISSUE TITLE
Can we show this progress bar inside LoadingController message?

### ISSUE THREAD

**Issue by ZaLiTHkA** [CharlesGrimont/angular-progress-bar#13]
I'd like to show *this* progress bar inside the overlap message created by `ionic-angular`, but I'm battling to work out how to do this.. Really hoping that it's not beyond the possibility of this module, but I'll only know if I ask.

Earlier I found [an SO question](https://stackoverflow.com/questions/41509721/ionic-2-progressbar-inside-loading-component-innerhtml-sanitize-issue) that sounded much like what I'm trying to achieve, but one of the comments on the selected answer states that "it doesn't seem's to work with an Angular2 component (such as <progressbar> from ng2-bootstrap)."

Is this something that `angular-progress-bar` could be adjusted to cater for? Or is it something that I would need to implement differently when building my UI?

>note: I'm still learning Angular, so please forgive me if this is a "silly" question with an obvious answer, because it's neither of those to me.

---

*edit:* Soon after posting this, I stumbled onto a page on Angular's [Dynamic Component Loader](https://angular.io/guide/dynamic-component-loader), which sounds like it might allow me to render this `<progress-bar>` component inside the markup used to render a new loading component popup. Am I going down the right road here?

**Comment by CharlesGrimont** [comment]
Did you find any way ?

**Comment by ZaLiTHkA** [comment]
sort of, yes.. I didn't quite have the time to try implement the "Dynamic Component Loader" idea (though I would still like to try that, at least to satisfy my own curiosity).

now inside my long-running method's `onProgress` callback, I create an HTML string that matches the output of `angular-progress-bar`, then pass it through Angular's `bypassSecurityTrustHtml` method. after by copying the styling rules you created into my page's SCSS file, essentially I'm manually rendering the same output as your component does. (:

I know it's a bit hacky, but this is just a temporary workaround for the moment, I'll fix it properly as soon as my boss gives me the time to..
