### ISSUE TITLE
Different colors according to %

### ISSUE THREAD

**Issue by ednilsonamaral** [CharlesGrimont/angular-progress-bar#2]
How can I change de background-color of .product-inner acordding with the %?

Example 1: if the % <= 20, then the background-color should be red
Example 2: if the % >= 20 & <=50, then the background-color should be yellow
Example 3: if the % > 50, then the background-color should be green

**Comment by CharlesGrimont** [comment]
Can you try version 1.0.1-beta3 ?

Synthax would be like
`<progress-bar [progress]="7" [color-degraded]="{'0': '#FFFFFF', '77': '#000000'}">
  </progress-bar>`

Where from 0 to 77 color will be #FFFFFF and then from 78 to 100 color will be #000000

Thanks by advance to make me a returns ...

**Comment by ednilsonamaral** [comment]
The new color works only above 77. Below 77, the color is default.

**Comment by CharlesGrimont** [comment]
Ok can you try 1.0.1-beta4 ??????

**Comment by CharlesGrimont** [comment]
1.0.2 version is stable and offers you the feature

**Comment by ednilsonamaral** [comment]
Thanks, @CharlesGrimont. Now works fine! I used as ` [color-degraded]="{ '0': 'red', '20': 'yellow', '50': 'green' }"`! :)
