### ISSUE TITLE
Progress Bar doesn't stay within container when at 100%

### ISSUE THREAD

**Issue by mjacobson7** [CharlesGrimont/angular-progress-bar#4]
I was experiencing this issue on my site.  I wanted to see if it was happening with the demo, and it is, so I wanted to let you know.

![2018-08-19_19-56-31](https://user-images.githubusercontent.com/18683764/44316682-1d0f0b00-a3ea-11e8-92b9-51a75ba6abff.png)

**Comment by mjacobson7** [comment]
Here's a close up if the other screenshot isn't clear enough.

![image](https://user-images.githubusercontent.com/18683764/44316704-37e17f80-a3ea-11e8-88f3-b02a2bc504bf.png)

**Comment by CharlesGrimont** [comment]
Let me know if version 1.0.7-beta1 resolve the problem, Thanks you for your comments !

**Comment by mjacobson7** [comment]
Hmmm... I'm getting an error once I install that specific version:

`ERROR in src/app/app-routing.module.ts(270,2): error TS2304: Cannot findname 'ProgressBarModule'.`

Any ideas?

**Comment by ZaLiTHkA** [comment]
@CharlesGrimont, did something funny happen when you tried to publish `1.0.7-beta1`?

I was using `1.0.5` in my project, which just updated to `1.0.7` and I'm getting the same error as @mjacobson7.

with that said, running `npm view anguar-progress-bar` shows some strange output for the versions:

* `dist-tags` shows `{ beta: '1.0.7-beta1', latest: '1.0.5' }`
* end of `versions` shows `['1.0.5', '1.0.6', '1.0.7-beta1', '1.0.7']`
* further along, the current `version` key shows `1.0.5`

when I do a straight up `npm i`, I get version `1.0.7` (and the issue mentioned above), installing `1.0.5` specifically fixes this issue.

---

*edit:* I just noticed the following diff in my `package-lock.json` file:

```diff
      "integrity": "sha1-SlKCrBZHKek2Gbz9OtFR+BfOkfU="
    },
    "angular-progress-bar": {
-      "version": "1.0.7",
-      "resolved": "https://registry.npmjs.org/angular-progress-bar/-/angular-progress-bar-1.0.7.tgz",
-      "integrity": "sha512--S4ekKd5dDTYqMb72eZtWYjxd8il5KRtc9bcvCllcQ3SbvSxP1TpwBSaNMzrvqblAMQ64HZdWf7jf1mpFFcEyBQ=="
+      "version": "1.0.5",
+      "resolved": "https://registry.npmjs.org/angular-progress-bar/-/angular-progress-bar-1.0.5.tgz",
+      "integrity": "sha512-ZR4N5VqrMnqTX2FclCvVqJ/plXja9fM7CvzWAS3U6jKHACWeGNvj3Ki3rWFT/89vblxpM7Gnvv7PtC71+f4x4Q==",
+      "requires": {
+        "tslib": "1.9.0"
+      }
    },
    "ansi-regex": {
      "version": "2.1.1",
```

does the missing `requires: {tslib: "1.9.0"}` from `1.0.7` perhaps explain the TypeScript error?

> note: I'm now building my project using a fork of this repo at version `1.0.5` to simplify the process of including custom fonts, so that "integrity" sum probably wouldn't match this official repository's sources.

**Comment by CharlesGrimont** [comment]
I will do necessary changes

**Comment by CharlesGrimont** [comment]
1.0.8 version must fix both issues !!!

let me know if it's ok.

Thanks for your feedback

**Comment by mjacobson7** [comment]
@CharlesGrimont Great! The original issue I reported is now fixed.  Thank-you!

**Comment by ZaLiTHkA** [comment]
Awesome, thanks.. I've just moved house and I don't have internet set up yet at home, so I'll check with 1.0.8 first thing Monday morning (GMT+2) and let you know. (:

**Comment by ZaLiTHkA** [comment]
My apologies... I did adjust the version in my `package.json` to allow `1.0.8` to install, then I got pulled into a meeting and forgot to reply when I got back.

So just to follow up; the dependency problem I asked about is now resolved. :)
